version: '3.9'

networks:
  public_net:
    driver: bridge
  lan_1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
#          gateway: 192.168.10.2
  lan_2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
#          gateway: 192.168.20.2
  lan_3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
#          gateway: 192.168.30.2

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: web_service
    networks:
      lan_3:
        ipv4_address: 192.168.30.100

  ws1:
    build:
      context: .
      dockerfile: Dockerfile-ws1
    privileged: true
    container_name: ws1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      lan_1:
        ipv4_address: 192.168.10.10


  ws2:
    build:
      context: .
      dockerfile: Dockerfile-ws2
    container_name: ws2
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      lan_1:
        ipv4_address: 192.168.10.11

  ws3:
    build:
      context: .
      dockerfile: Dockerfile-ws3
    container_name: ws3
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      lan_2:
        ipv4_address: 192.168.20.10


  outer_gw:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-outergw
    container_name: outer_gw
    ports:
      - "8080:80"
    networks:
      lan_3:
        ipv4_address: 192.168.30.2
      public_net:

  inner_gw:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-innergw
    container_name: inner_gw
    networks:
      lan_1:
        ipv4_address: 192.168.10.2
      lan_2:
        ipv4_address: 192.168.20.2
      lan_3:
        ipv4_address: 192.168.30.3
