server:
  port: 8088
#  servlet:
#    context-path: /api/v1
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        hbm2ddl:
          auto: update
      show_sql: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    package:
      trust-all: true

  jms:
    template:
      default-destination: chat.topic
    pub-sub-domain: yes



#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/test_db
#    username: root
#    password: 123456
#redis:
#  host: redis-10701.c16.us-east-1-2.ec2.redns.redis-cloud.com
#  port: 10701
#  username: default
#  password: BNX2ri1PlRocGCYx1id76NVHCnHQ7J7W
#mqtt:
#  host: tcp://localhost:9000
#  username: hungnq
#  password: 1111

